language: node_js
node_js:
- 6.3.1
deploy:
  provider: heroku
  api_key:
    secure: i31ACMqjqB58umXVMBjLDscKb8FFZnH7fgX5WXDr9WV+SXPM4Lf5zEeg8X7FZgwEnmerpXdcX/pukauGyiNE+EjAB81JxOhl++N1KHowM9FuBK35Y475reFHBUyWS0OluKBWo2q2Be8W2U1Bm6WJXBx3sdUb5F04FDhu0Q4QypjOFU/rnvjTDHE7J48U3IWVczPLR+Rcx4wqlL5yQY1BZNrLlWRoxVRNa/IRLR7n6iydOmbSYGBb9Vk1m8F8D8WQ3QBoQ281UUyAfxxnaC7t89CmO246aVA1n7pilxDd23thO3Md/ys6x7U9NbI+DcugbobRehzBqx5/vl4dLnkpV/VmPLaBQoMP2wB0EpJE3B9gwprV8NC3jNpOsZ/znVPhnfiZeB0i4OrprZRcnojr1N+30bsBeWwCWUZM0CCmu/cDKxsxbqpDtR1iYqGg9cgaE+QAt1Rbo9IX44u7Nj3jyDx2zsyrkJCQ00igLOQJ1MAJcPhjiBcGdcvBF0/5D3eImDpNQN6UBG6dn2ThsLvu9Gk1VJiT12QpEOgxnq//HfPVmfPCx/abN7+FPJ8gFfZ7PTg4L+/DXyyJSyt+Y9fGdRQmHRUgoF7vODK6OU4epEr9JdeRyqCrdcdjK0qQprlzj2xMBQkV8SiAqQ6t1vucO4H4FVl6yOwAeXvrvtzhQII=
  app: ci-show-case
  on:
    repo: OrencioRodolfo/ci-demo
